### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by nordelite** [CPScript/Termux-Hotspot#1]
Hey how do I do this via ADB Shell? 

And what's the minimum Android version this Termux-Hotspot could be made on?

**Comment by 0u44** [comment]
`hostapd`(the dependency that makes this script work) can work on mostly any termux version, but it depends on the hardware of the phone... running it through ADB Shell may require specific configurations. You need to ensure that your device supports the necessary Wi-Fi functionalities and that you have the appropriate permissions.
